[tool.ruff]

# Enable all rules
select = ["ALL"]

# Assume Python 3.10
target-version = "py310"

# cache directory 
cache-dir = "~/.cache/ruff"

[tool.ruff.lint]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
